[[policy]]
name = "allow-upstream"
  [[policy.rule]]
  action = "ALLOW"
  methods = ["GET", "HEAD", "POST"]
  url_pattern = "http://upstream/**"
  inspect_payload = true
  allow_private_upstream = true
